### ISSUE TITLE
Long pages are difficult to navigate

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#119]
Pages with lots of entries, like community pages and resource pages, can be difficult to navigate. Long pages are OK for long-form reading, but when you need to scan information, or find a specific piece of information on a page, long pages benefit from making it easier to understand the content at a glance.

This can be done with information architecture, navigation, typography, or other layout tricks, but at the end of the day, the goal is to convey a page's contents as quickly and clearly as possible. Right now, we have too many pages that require some real effort to parse.

### todo
- [ ] Identify a few specific pages that need improvement
- [ ] Perform a qualitative analysis of these pages
- [ ] Link to internal/external research on in-page navigation
- [ ] Suggest solutions to improve them
- [ ] Bring to the team for discussion

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
