### ISSUE TITLE
Use tags and categories more consistently

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#120]
Our content is structured with tags and categories to make content easier to find and sort, but there's a lot of redundancy between the taxonomy of our tags and categories — and we don't have much good information about how people use this organization to find what they're looking for.

We need to understand how we're using tags and categories, learn industry best practices for organization, and discover how our readers use this navigation aid on our site. Then we can go in and do the hard work of updating our tags and categories to better suit the content and our readers' needs.

### todo
- [x] Gather information about our categories and tags
- [x] Find number of categories
- [x] Find number of tags
- [x] Find number of posts associated with each
- [ ] Identify redundancy
- [ ] Collect analytics on tag/category pages
- [ ] Identify similar sites for comparative analysis
- [ ] Analyze how those site use tags/categories/other
- [ ] Link to internal or external research
- [x] Identify possible solutions
- [x] Bring to the team for discussion

**Comment by thisisdano** [comment]
This issue has a lot of moving parts

**Comment by jeremyzilar** [comment]
Here are all **570** of our tags: https://digital.gov/tag/
Here are all **23** of our categories: https://digital.gov/categories/

To clean up and focus the tags/topics that we have on digital.gov, I recommend that we:

- [ ] remove all agency names from the tags to a new taxonomy or data file
- [ ] remove all community names from the tags to a new taxonomy or data file
- [ ] remove or merge any tags that are purely used for organization

_NOTE: If we are removing tags, we'll need to find, replace, and remove these tags in each of the posts that have them. This is not hard, just a step we'll need to take._ 

Next, I suggest we:

- [ ] merge tags and categories into **"topics"**
- [ ] explore making topics hierarchical

```
- UX
  - user-research
  - usability testing
  - ...
```

**Comment by jeremyzilar** [comment]
See also https://github.com/GSA/digitalgov.gov/issues/692

**Comment by jeremyzilar** [comment]
We did this! 🎉 in Demo
