### ISSUE TITLE
Audit of our Navigation structure

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#130]
What is working, what is not working in our navigation?

- - -

### Todo:
- [ ] Document the contents of our current navigation
- [ ] Document the navigation mechanism
- [ ] Collect examples of other navigation options
- [ ] Find any relevant research (our own, or elsewhere)
- [ ] Suggest improvements to our navigation

Feel free to ✏️ this list.

**Comment by thisisdano** [comment]
Feel free to edit this list.

### Todo:
- [ ] Document the contents of our current navigation
- [ ] Document the navigation mechanism
- [ ] Collect examples of other navigation options
- [ ] Find any relevant research (our own, or elsewhere)
- [ ] Suggest improvements to our navigation

**Comment by ToniBonittoGSA** [comment]
Just some notes since I'll be out next week: 

## Pages

Home (https://www.digitalgov.gov / https://www.digital.gov)

[Events](https://www.digitalgov.gov/events/)
 - DigitalGov University
 - Video Library (to YouTube channel)

[Communities](https://www.digitalgov.gov/communities/)
 - [Manage Your Listserv Subscription](https://www.digitalgov.gov/communities/manage-your-subscription/) 
 - Agile/Lean
 - AI (now on gsa.gov as Emerging Citizen Tech program)
 - Blockchain (now on gsa.gov as Emerging Citizen Tech program)
 - Business USA
 - Challenges & Prizes
 - Community Solutions
 - Crowdsourcing & Citizen Science
 - Government Contact Center Council (G3C)
 - Government Customer Experience (CX)
 - MobileGov
 - Multilingual
 - Open Data
 - OpenGov
 - Plain Language Action and Information Network
 - SocialGov (now on gsa.gov as Emerging Citizen Tech program)
 - User Experience (UX)
 - Video Production Pros
 - Virtual/Augmented Reality (now on gsa.gov as Emerging Citizen Tech program)
 - Web Content Managers

[Services](https://www.digitalgov.gov/services/)
 - Challenges & Prizes
 - Content Management (Sites)
 - eCPIC
 - Data.gov
 - Metrics (DAP)
 - U.S. Digital Registry (MobileGov, SocialGov)
 - Federal CrowdSource Mobile Testing Program (MobileGov)
 - Search
 - USA.gov Short URLs

_Should we add anything else under our Services and Programs umbrella? (IRL proposed name change from OPP)_

[Resources](https://www.digitalgov.gov/resources/)
 - (many pages, some go 2 or 3 levels down)

[About](https://www.digitalgov.gov/about/)
 - [Site Policies](https://www.digitalgov.gov/about/policies/) (link in footer; is a sub-page of About Us)
 - [Contact Us](https://www.digitalgov.gov/contact-us/) (is not a sub-page of About Us; just moved there for space)

[Join DigitalGov](https://www.digitalgov.gov/join-digitalgov/)
 - [Open Opportunities](https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/) (is not a sub-page of Join DG; just moved there for space)
 -- How Open Opportunities Works
 -- Open Opportunities Task Creator Toolkit
 -- Open Opportunities Terms of Use

---

## Categories

Challenges
 - Crowdsourcing & Citizen Science

Code
 - API
 - Data

Content
 - Video
 - Writing

Managing Digital
 - Strategy & Policy

Metrics

Mobile

Social Media

UX
 - Accessibility
 - Design
 - User Testing


_Would like to add:_ 
**Emerging Tech** (AI, AR, VR, Blockchain, Machine Learning, IoT, Robotics, etc.)
https://en.wikipedia.org/wiki/List_of_emerging_technologies 
https://en.wikipedia.org/wiki/Emerging_technologies 
_Emerging Tech_ and _Emerging technologies_ are popular search terms, and new categories on other tech blogs.

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
