### ISSUE TITLE
Work on the Digital.gov APIs

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1387]
We need to work on bringing our APIs up to the GSA standards https://open.gsa.gov/api/

**Here are a few of the things we need to tackle:**
- [ ] Add to the GSA API Directory
- [ ] Adopt API.Data.gov
- [ ] Have version numbers
- [ ] Public documentation ([link](https://github.com/GSA/digitalgov.gov/wiki/APIs))
- [ ] Feedback Mechanism _(GitHub repo or email address)_
- [ ] Open API Spec File
- [ ] Endpoint design

Related: https://github.com/GSA/digitalgov.gov/issues/1247

**Comment by gbinal** [comment]
More details on these - https://github.com/GSA/api-standards

**Comment by jeremyzilar** [comment]
## Todo by Jan 31

- [ ] Verify that all the APIs are working as intended
- [ ] have @gbinal update the API endpoints
- [ ] Have versioning considered and represented in the endpoint URLs
- [ ] Document how APIs will be updated and how people will be notified of updates ([link](https://github.com/GSA/open-gsa-redesign/blob/apidocs-digitalgov-20191018/_apidocs/digitalgov.md))
- [ ] Document how people can submit feedback around the API ([link](https://github.com/GSA/open-gsa-redesign/blob/apidocs-digitalgov-20191018/_apidocs/digitalgov.md))
- [ ] Update the spec file `openapi.yml` [see DAP for examples](https://open.gsa.gov/api/dap/#openapi-specification-file)
- [ ] publish the API endpoints page in the footer of Digital.gov

## Digital.gov Docs
- [ ] explore if the HUGO API endpoints can support versioning
- [ ] Set up CircleCi tests for API endpoints
