### ISSUE TITLE
Event generator generating mangled date in front matter

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#159]
We just got the following in an event's front matter.

`date: 2017-12-12 9:00am:00 -0400`

Let's check and make sure event date is being parsed and processed correctly in the generator javascript.

### todo
- [x] try to reproduce the error
- [x] follow up with @jthalls 
- [x] assure that dates output in the proper format

**Comment by jeremyzilar** [comment]
This looks like the `am` was added in by @jthalls.

There are a few things we can change here:
- better field validation
- a time picker/dropdown
- more clear helper text

**Comment by thisisdano** [comment]
Gonna close this issue. We can add a new one to do some specific validation, etc.
