### ISSUE TITLE
Event: January Plain Language Monthly Meeting

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#298]
# Plain Language Monthly Meeting

**Date:** Tuesday, Jan 10, 2018, 2-3pm ET
**Summary** _(one sentence)_ — The January meeting of PLAIN

**Description** _(min ~200 words)_ — 
Join us for the first Plain Language Action and Information Network (PLAIN) Monthly meeting of 2018. 

**Event Page** https://www.digitalgov.gov/event/january-plain-monthly-meeting/

**Related:**
- [https://www.plainlanguage.gov/](https://www.plainlanguage.gov/)
- [Plain Language Community of Practice](https://www.digitalgov.gov/communities/plain-language/)
---
**Tasks:**
- [x] 30min meeting w/ presenters
- [x] Send calendar invite once event date has been determined
- [x] Request video title card
- [x] Create event in Eventbrite
- [x] Create event in YouTube live
- [x] Post event page on DigitalGov
- [x] Schedule emails through Eventbrite
- [x] Schedule real time captioning through FedRelay (http://www.fedrcc.us//Enter.aspx?EventID=3527667&CustomerID=321)
- [x] Request title card
- [x] Identify moderator for live chat/online questions and send moderator script
- [x] Schedule tech check with presenters to review online platform and logistics of event
- [x] Work with DG team to promote via Social Media platforms
- [x] Track registration and provide event partner weekly registration updates
- [x] Set up evaluation in Google Forms and share with POC (https://docs.google.com/forms/d/1Otw156pWhmGcEIP3Ge_-CfEYdGs-o_85fgxudd0Ldvs/edit?usp=sharing
  )
- [x] Update metrics spreadsheet
- [x] Schedule post event/training retro
- [x] Add title card immediately following event
- [x] Send post-event email with link to video, evaluation, and any additional resources
- [ ] Share evaluation results with event partner and presenters
- [ ] Conduct retro

**Comment by jeremyzilar** [comment]
I think we can do more with this copy, especially if we plan on reusing it for each meeting.

**Comment by thisisdano** [comment]
![plain-january-2018](https://user-images.githubusercontent.com/11464021/34785770-f8e573a6-f5e6-11e7-9521-08b8b2bb9563.png)
