### ISSUE TITLE
Make accessibility changes from audit

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#434]
The homepage accessibility audit results are here: https://docs.google.com/spreadsheets/d/1fEOqYUJqQVhg4VaHI7t21nSIon2jSA-EvmBQfIkJukg/edit#gid=854558714
We need to make the changes necessary to remediate these issues — and, when possible, to search for similar issues across other site pages.

### todo
- [x] Fix `go to top` button
- [x] Assure all links have a `:focus` state
- [ ] "The visual focus does not remain within a modal dialog box until closed" — find out what this refers to and address
- [x] Add label to search field
- [x] `Read more` links need aria label or title attributes
- [x] Add `alt` attribute to GSA logo
- [x] See below
> News image links have alt description different from the actual link. This results in a confusing experience for a screen reader user. ex. "A video call with 4 users..." is not what the image is there for
- [x] "Alt tags for DAP and Challenge.gov images does not contain the text in the images" — I don't think this is really important as the text in these images is not important, but make sure
- [x] Address the following contrast issues
  - [x] White "Search" text on button
  - [x] Red hover text on green in menu
  - [x] Read more text on button
  - [x] Red "#ff5049" text on white - Events section
  - [x] Pink text in footer
- [x] Address following header issues:
  - [x] Articles in each section have the same heading level as the section they are in. Example: h3 - Latest news h3 - A better digital gov
  - [x] "Latest News" should be h2, "A better digital gov" should be h3
- [x] Fix `skip nav` functionality
- [x] Assure all `id`s are unique

### it's done when:
- [ ] we can confirm that the homepage errors in the document no longer appear on the homepage
- [ ] identified systemic accessibility errors no longer appear on the a subset of pages we identify to check
- [ ] pull request is merged
