### ISSUE TITLE
Publish an MVP of our Style Guide

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#484]
## it should include individual pages for
- [ ] Voice and Tone https://github.com/GSA/digitalgov.gov/issues/585 
- [ ] Grammar and Spelling https://github.com/GSA/digitalgov.gov/issues/585
- [ ] Digital.gov branding https://github.com/GSA/digitalgov.gov/issues/585
- [ ] Image Use https://github.com/GSA/digitalgov.gov/issues/585

## criteria for done
- [ ] we should feel comfortable publishing

## it's done when …
- [ ] it has been published
- [ ] it has been linked to from the govt-wide style guide page
