### ISSUE TITLE
Please combine Required Web Content and Links with Checklist of Requirements for Federal Websites and Digital Services

### ISSUE THREAD

**Issue by bruce-usab** [GSA/digitalgov.gov#675]
## These are two great resources:
- [ ] http://digital.gov/resources/required-web-content-and-links/
- [ ] http://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/
- [ ] but right now, website managers have to look at both, and with checklist, it is not as clear as perhaps it could be which are actually requirements, and which are just best practices

## it's done when …
- [ ] These two resources are better integrated with each other
- [ ] There is some prioritization.  Which are driven by statute?  Which are driven by Executive Order?  Which ones are newer and therefore more important?

Thank!

**Comment by jeremyzilar** [comment]
This is a great idea @bruce-usab — apologies it took this long to get to it. We will be working on this in the coming month. Will loop you in for 👀

**Comment by jeremyzilar** [comment]
We are working on this :)
